doctrine:
  dbal:
    url: '%app.database.url%'
    driver: 'pdo_pgsql'
    server_version: 10.11
    charset: UTF8

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/app/mapping'
        prefix: 'App\Domain'
        alias: App
