home:
    path: /
    controller: App\UI\Http\Home\HomeController::index

contest:
    path: /contest
    controller: App\UI\Http\Contest\ContestController::create

contest_view:
    path: /contest/{id}
    controller: App\UI\Http\Contest\ContestController::view

contest_round_play:
    path: /contest/{id}/round/play
    controller: App\UI\Http\Contest\ContestController::nextRound

history:
    path: /history
    controller: App\UI\Http\History\HistoryController::show